# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=32)),
                ('embed_text', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=32)),
                ('embed_text', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
